# Generated by Django 2.0.3 on 2018-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('definition', models.TextField()),
                ('part_of_speech', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
    ]
